apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-80
  namespace: hackazon
  labels:
    app: nginx-ingress
    cis.f5.com/as3-tenant: hackazon
    cis.f5.com/as3-app: nginx-ingress-80
    cis.f5.com/as3-pool: nginx-ingress-pool-80
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx-ingress