apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-443
  namespace: hackazon
  labels:
    app: nginx-ingress
    cis.f5.com/as3-tenant: hackazon
    cis.f5.com/as3-app: nginx-ingress-443
    cis.f5.com/as3-pool: nginx-ingress-pool-443
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 443
    targetPort: 443
    protocol: TCP
  selector:
    app: nginx-ingress