apiVersion: v1
kind: Service
metadata:
  name: glusterfs-cluster
  namespace: hackazon
spec:
  ports:
  - port: 1
---
apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
  namespace: hackazon
subsets:
  - addresses:
      - ip: 10.1.20.20
    ports:
      - port: 1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-gsfs-k8s
  namespace: hackazon
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: gsfs
  glusterfs:
    endpoints: glusterfs-cluster
    path: k8s-udf-storage
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-gsfs-k8s
  namespace: hackazon
  labels:
    app: pvc-gsfs-k8s
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: gsfs