## ----------------------------------------------------------------------------
## ..:: NGINX-Plus Servers Installation ::..
## ----------------------------------------------------------------------------

- hosts: nginx_plus_servers
  remote_user: root
  tasks:

    - name: Set timezone to Europe/Rome
      timezone:
        name: Europe/Rome

    - name: Upgrading all packages to the latest version
      apt:
        update_cache: yes
        upgrade: dist

    - name: setting hostname
      template:
        src: hostname.j2
        dest: /etc/hostname

    - name: Enable rc.local
      template:
        src: rc.local.j2
        dest: /etc/rc.local
        mode: '0755'

    - name: Reboot nginx-plus  and wait for it to restart
      reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami

    - name: NGINX Plus licensing - Preparing filesystem
      file:
        path: /etc/ssl/nginx
        state: directory

    - name: Copying license key and certificate
      copy:
        src: /home/ubuntu/licenses/nplus/nginx-repo.{{ item }}
        dest: /etc/ssl/nginx/
      with_items:
        - key
        - crt

    ## Installing needed software
    - name: Installing needed software on Ubuntu Server
      apt:
        pkg:
        - apt-transport-https
        - lsb-release
        - ca-certificates
        - python2.7

    # Add specified repository into sources list using specified filename.
    ## Adding NGINX Repositories
    - name: Adding NGINX apt-key
      apt_key:
        url: https://nginx.org/keys/nginx_signing.key
        state: present

    - name: Adding NGINX apt reporisotries
      shell: echo "deb https://plus-pkgs.nginx.com/ubuntu `lsb_release -cs` nginx-plus\n" > /etc/apt/sources.list.d/nginx-plus.list

    ## Importing 90nginx
    - name: Importing 90nginx
      get_url:
        url: https://cs.nginx.com/static/files/90nginx
        dest: /etc/apt/apt.conf.d/90nginx

    - name: Upgrading all packages to the latest version
      apt:
        update_cache: yes
        upgrade: dist

    ## Installing needed software
    - name: Installing needed software on Ubuntu Server
      apt:
        pkg:
        - nginx-plus
        - nginx-plus-module-njs

    ## Staring NGINX Server
    - name: Starting NGINX Plus Server
      service:
        name: nginx
        state: started

    - name: Copy resolv.conf file
      copy:
        src: resolv.conf
        dest: /etc/resolv.conf

    - name: Remove resolv.conf link
      file:
        path: /etc/resolv.conf
        state: absent

    - name: Copy resolv.conf file on cluster's master and nodes
      copy:
        src: resolv.conf
        dest: /etc/resolv.conf

#    - name: Copy hosts file
#      copy:
#        src: hosts
#        dest: /etc/hosts
