{
    "class": "AS3",
    "action": "deploy",
    "persist": true,
    "declaration": {
       "class": "ADC",
       "schemaVersion": "3.0.0",
       "id": "udf-system-services-2020051102",
       "label": "UDF System Services",
       "remark": "Needed Infrastructure Services",
       "arcadia": {
          "class": "Tenant"
         }
       }
    }